-- Northstar Stocks schema for Supabase (PostgreSQL).
-- Run this once in Supabase Dashboard > SQL Editor.
--
-- IMPORTANT: this creates the database schema, but the current app backend in
-- server/db.js uses Node's built-in SQLite driver. It will NOT connect to these
-- tables until the backend is migrated to PostgreSQL/Supabase. Keep the
-- service_role key on the server only; never expose it in browser code.

begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  cash_cents bigint not null default 10000000 check (cash_cents >= 0),
  created_at bigint not null,
  is_demo integer not null default 0 check (is_demo in (0, 1))
);
create unique index if not exists users_email_ci_idx on public.users (lower(email));

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at bigint not null,
  created_at bigint not null,
  linked_user_id bigint references public.users(id) on delete cascade
);
create index if not exists idx_sessions_user on public.sessions (user_id);

create table if not exists public.assets (
  symbol text primary key,
  name text not null,
  sector text not null,
  exchange text not null,
  kind text not null default 'stock' check (kind in ('stock', 'etf')),
  color text not null default '#5265a8',
  base_price_cents bigint not null check (base_price_cents > 0),
  base_change_percent double precision not null default 0,
  active integer not null default 1,
  featured integer not null default 0
);

create table if not exists public.watchlists (
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null references public.assets(symbol),
  primary key (user_id, symbol)
);

create table if not exists public.positions (
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null references public.assets(symbol),
  quantity bigint not null check (quantity > 0),
  average_cost_cents bigint not null check (average_cost_cents > 0),
  primary key (user_id, symbol)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  symbol text not null references public.assets(symbol),
  side text not null check (side in ('buy', 'sell')),
  type text not null check (type in ('market', 'limit')),
  quantity bigint not null check (quantity > 0),
  limit_price_cents bigint,
  filled_price_cents bigint,
  status text not null check (status in ('pending', 'filled', 'cancelled')),
  created_at bigint not null,
  filled_at bigint
);
create index if not exists idx_orders_user on public.orders (user_id, created_at desc);
create index if not exists idx_orders_pending on public.orders (status, symbol);

create table if not exists public.cash_transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null check (type in ('top_up', 'withdrawal')),
  amount_cents bigint not null check (amount_cents > 0),
  balance_after_cents bigint not null check (balance_after_cents >= 0),
  created_at bigint not null
);
create index if not exists idx_cash_transactions_user
  on public.cash_transactions (user_id, created_at desc, id desc);

create table if not exists public.transfer_methods (
  id bigint generated by default as identity primary key,
  details text not null,
  active integer not null default 1 check (active in (0, 1)),
  created_at bigint not null
);

create table if not exists public.transfer_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  type text not null check (type in ('deposit', 'withdrawal')),
  amount_cents bigint not null check (amount_cents between 100 and 10000000),
  method_id bigint references public.transfer_methods(id),
  details text not null,
  reference text not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'rejected', 'cancelled')),
  review_note text,
  reviewed_by bigint references public.users(id),
  reviewed_at bigint,
  created_at bigint not null,
  request_key text not null,
  unique (user_id, request_key)
);
create index if not exists idx_transfers_user on public.transfer_requests (user_id, id desc);
create index if not exists idx_transfers_status on public.transfer_requests (status, id desc);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  active integer not null default 1,
  created_at bigint not null
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.users(id),
  target_user_id bigint references public.users(id),
  action text not null,
  detail text not null,
  created_at bigint not null
);

-- Seed the app's built-in market catalog. Prices are stored in cents, as in SQLite.
insert into public.assets
  (symbol, name, sector, exchange, kind, color, base_price_cents, base_change_percent, featured)
values
  ('AAPL',  'Apple Inc.',                 'Technology', 'NASDAQ',    'stock', '#252d40', 24736,  1.24, 1),
  ('NVDA',  'NVIDIA Corp.',                'Technology', 'NASDAQ',    'stock', '#76b900', 18247,  2.83, 1),
  ('MSFT',  'Microsoft Corp.',             'Technology', 'NASDAQ',    'stock', '#4285c5', 51291,  0.94, 1),
  ('GOOGL', 'Alphabet Inc.',               'Technology', 'NASDAQ',    'stock', '#e85b51', 19254, -0.62, 0),
  ('AMZN',  'Amazon.com Inc.',             'Consumer',   'NASDAQ',    'stock', '#ef9d32', 22716,  1.37, 0),
  ('TSLA',  'Tesla Inc.',                   'Automotive', 'NASDAQ',    'stock', '#df4848', 27683, -1.18, 1),
  ('META',  'Meta Platforms Inc.',         'Technology', 'NASDAQ',    'stock', '#3679da', 70235,  2.06, 0),
  ('AMD',   'Advanced Micro Devices',      'Technology', 'NASDAQ',    'stock', '#373e50', 16642, -0.84, 0),
  ('SPY',   'SPDR S&P 500 ETF',            'ETF',        'NYSE Arca', 'etf',   '#394fc1', 66038,  0.73, 1),
  ('QQQ',   'Invesco QQQ Trust',           'ETF',        'NASDAQ',    'etf',   '#5b43bd', 58827,  1.12, 1),
  ('DIA',   'SPDR Dow Jones ETF',          'ETF',        'NYSE Arca', 'etf',   '#5b8d9c', 47242,  0.35, 0),
  ('JPM',   'JPMorgan Chase & Co.',        'Finance',    'NYSE',      'stock', '#326b91', 30218,  0.45, 0)
on conflict (symbol) do nothing;

insert into public.settings (key, value)
values ('trading_enabled', '1')
on conflict (key) do nothing;

insert into public.announcements (title, body, active, created_at)
select
  'A clearer way to follow the market',
  'Welcome to Northstar. Explore stocks, build a watchlist, and practice your strategy with a paper trading account.',
  1,
  (extract(epoch from clock_timestamp()) * 1000)::bigint
where not exists (select 1 from public.announcements);

-- The app uses its own server-side cookie sessions and password hashes (not Supabase Auth).
-- Keep all tables inaccessible to browser roles; a trusted server connection must perform
-- all reads/writes. Supabase service_role bypasses RLS and must remain server-only.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'sessions', 'assets', 'watchlists', 'positions', 'orders',
    'cash_transactions', 'transfer_methods', 'transfer_requests',
    'announcements', 'settings', 'audit_log'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end
$$;

grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
